version: '3.8'

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: netlocal_mailpit
    profiles: ["tier1"]
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
    networks:
      - localnet_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`devmail.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"