version: '3.8'

services:
  webmail:
    image: lscr.io/linuxserver/snappymail:latest
    container_name: netlocal_webmail
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - webmail_data:/data
    networks:
      - localnet_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webmail.rule=Host(`mail.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"

volumes:
  webmail_data: