logger:
  file: /var/log/open5gs/amf.log

amf:
  sbi:
    server:
      - address: 0.0.0.0
    clients:
      - address: smf
  ngap:
    server:
      - address: 0.0.0.0
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 1