version: '3.8'

services:
  powerdns:
    image: powerdns/pdns-auth-mysql:4.8.0
    container_name: netlocal_powerdns
    depends_on:
      - postgres
    environment:
      - PDNS_gmysql_host=postgres
      - PDNS_gmysql_port=5432
      - PDNS_gmysql_user=powerdns
      - PDNS_gmysql_password=${POSTGRES_PASSWORD}
      - PDNS_gmysql_dbname=powerdns
      - PDNS_api=yes
      - PDNS_api_key=${POWERDNS_API_KEY}
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=${POWERDNS_API_KEY}
    networks:
      localnet_backbone:
        ipv4_address: 169.254.0.3
      localnet_default:
    volumes:
      - registry_data:/var/lib/powerdns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.powerdns.rule=Host(`registrar.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"

volumes:
  registry_data: