version: '3.8'

services:
  squid:
    image: sameersbn/squid:latest
    container_name: netlocal_squid
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf:ro
      - squid_data:/var/spool/squid
    networks:
      - localnet_default

volumes:
  squid_data: