version: '3.8'
services:
  localstack:
    image: localstack/localstack:3.0
    profiles: ["tag-cloud"]
    container_name: netlocal_localstack
    environment:
      - SERVICES=s3,lambda,dynamodb,sqs
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - localnet_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.localstack.rule=Host(`localstack.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"

volumes:
  localstack_data: