global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'netlocal'
    static_configs:
      - targets:
        - 'netlocal_traefik:8080'
        - 'netlocal_coredns:9153'
        - 'netlocal_postgres:9187'
        - 'netlocal_redis:9121'
        - 'netlocal_minio:9000'