version: '3.8'

services:
  trivy:
    image: aquasec/trivy:latest
    profiles: ["tag-security"]
    container_name: netlocal_trivy
    command: server --listen 0.0.0.0:8080
    networks:
      - localnet_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trivy.rule=Host(`trivy.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    profiles: ["tag-security"]
    container_name: netlocal_zap
    command: zap.sh -daemon -host 0.0.0.0 -port 8090
    networks:
      - localnet_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zap.rule=Host(`zap.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"