# docker-compose.dns.coredns.yml
services:
  dns:
    image: coredns/coredns:1.11.1
    container_name: netlocal_dns
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./config/dns/coredns/Corefile:/etc/coredns/Corefile:ro
      - ./config/dns/coredns/zones:/etc/coredns/zones:ro
    networks:
      - localnet_backbone
    labels:
      - "netlocal.layer=backbone"