version: '3.8'

services:
  dns:
    image: coredns/coredns:1.11.1
    container_name: netlocal_dns
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./config/Corefile:/etc/coredns/Corefile:ro
      - ./config/zones:/etc/coredns/zones:ro
    networks:
      localnet_backbone:
        ipv4_address: 169.254.0.2
    restart: unless-stopped
    labels:
      - "netlocal.component=dns"