version: '3.8'

services:
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: netlocal_seaweedfs
    command: server -dir=/data -s3
    volumes:
      - storage_data:/data
    networks:
      - localnet_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seaweedfs.rule=Host(`s3.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"
      - "traefik.http.services.seaweedfs.loadbalancer.server.port=8333"
      - "netlocal.component=storage"

volumes:
  storage_data: