version: '3.8'

services:
  dovecot:
    image: dovecot/dovecot:latest
    container_name: netlocal_dovecot
    volumes:
      - mta_data:/var/mail
      - ./config/dovecot.conf:/etc/dovecot/dovecot.conf:ro
    networks:
      - localnet_default
    depends_on:
      - stalwart
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dovecot.rule=Host(`imap-heavy.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"
      - "traefik.http.services.dovecot.loadbalancer.server.port=143"