version: '3.8'

services:
  gemini:
    image: gemini/gemini-server:latest
    profiles: ["tag-legacy"]
    container_name: netlocal_gemini
    networks:
      - localnet_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gemini.rule=Host(`gemini.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"