version: '3.8'

services:
  relay:
    image: ghcr.io/mailu/postfix:latest
    container_name: netlocal_postfix_relay
    environment:
      - RELAYHOST=[smtp.gmail.com]:587
      - RELAYHOST_USERNAME=${EXTERNAL_SMTP_USER}
      - RELAYHOST_PASSWORD=${EXTERNAL_SMTP_PASS}
    networks:
      - localnet_default
    restart: unless-stopped
    depends_on:
      - stalwart
    labels:
      - "netlocal.component=email-relay"