services:
  postfix:
    image: boky/postfix:latest
    container_name: netlocal_postfix
    environment:
      - RELAYHOST=${SMTP_RELAYHOST:-}
      - ALLOWED_SENDER_DOMAINS=${NETLOCAL_ROOT_DOMAIN:-net.local}
    networks:
      - localnet_default
    labels:
      - "netlocal.component=mail-relay"
    stop_grace_period: 30s

networks:
  localnet_default:
    external: true
