services:
  dovecot:
    image: dovecot/dovecot:latest
    container_name: netlocal_dovecot
    volumes:
      - dovecot_data:/var/vmail
      - ./dovecot.conf:/etc/dovecot/dovecot.conf:ro
    networks:
      - localnet_default
    labels:
      - "netlocal.component=imap"
    stop_grace_period: 30s

volumes:
  dovecot_data:

networks:
  localnet_default:
    external: true
