version: '3.8'

services:
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.7.0
    profiles: ["tag-chaos"]
    container_name: netlocal_toxiproxy
    command: --host=0.0.0.0
    networks:
      - localnet_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.toxiproxy.rule=Host(`chaos.${NETLOCAL_ROOT_DOMAIN:-net.local}`)"

  pumba:
    image: gaiaadm/pumba:latest
    profiles: ["tag-chaos"]
    container_name: netlocal_pumba
    command: --interval 5m netem --duration 1m delay --time 1000 --jitter 500
    cap_add:
      - NET_ADMIN
    networks:
      - localnet_default